name: Release githubactions

on:
  workflow_dispatch:
    workflows: [Continuous Integration]
    types:
      - complete

jobs:
  release:
    name: Release githubactions
    uses: ./.github/workflows/base-outcloud-release.yaml
    with:
      distribution: githubactions
    secrets: inherit
    permissions: write-all
