name: Release githubactions

on:
  workflow_dispatch:
  #  release:
  #    types: [published]
jobs:
  release:
    name: Release githubactions
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: githubactions
    secrets: inherit
    permissions: write-all
